### ISSUE TITLE
Don't call it CutefishOS in About on other distros

### ISSUE THREAD

**Issue by philmmanjaro** [cutefishos/settings#14]
Based on some feedback we had after doing our CutefishDE spin, some think we are developing another distro. Maybe add a more generic approach in About window about CutefishOS. It is fine to call it as it when it is really CutefishOS. What do you think?

**Comment by reionwong** [comment]
Yes, good suggestion, we will change to Cutefish on other distributions

**Comment by reionwong** [comment]
how do you feel?
![Screenshot from 2021-06-08 00-24-42](https://user-images.githubusercontent.com/9636382/121055661-0a129300-c7f0-11eb-875b-addc2f1bab8a.png)

**Comment by felixonmars** [comment]
LGTM, thanks :)

**Comment by philmmanjaro** [comment]
looked at the code. Seems fine solution for us too.
