### ISSUE TITLE
💡 : Need sound settings

### ISSUE THREAD

**Issue by joe733** [cutefishos/settings#29]
As of now (`0.4`) there's no way to adjust audio neither on settings, nor on panel.

![photo_2021-10-21_11-56-34](https://user-images.githubusercontent.com/38415384/138223077-45333b78-6094-4dfb-a349-acceec696cd8.jpg)

**Comment by chaudharyjatin115** [comment]
Fixed it's there on panel now

**Comment by gfubing** [comment]
为什么我的电脑要添加:[Mapping Inter-Mic]
device-strings = hw:%f,6
channel-map = left,right
paths-input=analog-input-internal-mic multichannel-input
priority = 9
direction = input
代码才能正常录音

**Comment by joe733** [comment]
> Fixed it's there on panel now

Yup, I see the speaker on the power panel, but the mic control is missing and so is sound configuration (select/balance/test) from the settings application.

**Comment by brandnkdavis** [comment]
![Screenshot_20241208_184443](https://github.com/user-attachments/assets/18867104-cec2-45e4-a55a-dd3f9e6d0d47)
LOVE your OS and am willing to help in ANYWAY I can.  I am having this issue. I can't select an audio output device at all. It would be very helpful to have a highlight displayed around the selected output/input device same as used for the power modes selector.
