### ISSUE TITLE
Duplicated "Wired Connection" shown in "WLAN" when only one ethernet adapter is present

### ISSUE THREAD

**Issue by felixonmars** [cutefishos/settings#3]
There is no Wi-Fi device in the VM, but the settings window shows a "Wired Connection" inside the WLAN frame:

![2021-05-26-050008-52d23b](https://user-images.githubusercontent.com/1006477/119567741-45b86080-bddf-11eb-8b88-c8df61b59b59.png)

**Comment by rekols** [comment]
it has been fixed :)
