### ISSUE TITLE
Bluetooth cannot be used

### ISSUE THREAD

**Issue by weclix** [cutefishos/settings#39]
> _system：_**archlinux**

> desktop：**Built on the latest code, version 0.6**

> _feature：_

**1.After turning off the Bluetooth option in the setting, turn it on again, and the settings window will be closed.
2.Use the terminal to open cutefish-settings and enter the Bluetooth option. The window shows that Bluetooth is turned on, but there is no Bluetooth device list, and the terminal does not have any information about Bluetooth.**

> _other：_

**Three devices turn on Bluetooth and wait for the link. 
The bluetooth.service of the pc has been started
no error message is seen when executing `systemctl status bluetooth`.
The bluetooth device is not locked after executing `rfkill list`**

**Comment by BenitzCoding** [comment]
Do `$ apt install blueman` and restart. That should get your bluetooth working!

**Comment by weclix** [comment]
> 

I will try to install blueman at night, thank you.But the Bluetooth of settings is still not available

**Comment by weclix** [comment]
> Do `$ apt install blueman` and restart. That should get your bluetooth working!

thank you. The problem has been solved
