### ISSUE TITLE
Opening Display settings opens WLAN settings

### ISSUE THREAD

**Issue by Ar7hurz1nh0** [cutefishos/settings#62]
The title says it all, but here's some images showing the problem
![image](https://user-images.githubusercontent.com/54512246/154481374-9f368184-79da-4148-9c90-27be2c9f49bc.png)
![image](https://user-images.githubusercontent.com/54512246/154481413-eccada5d-4059-450a-9b8f-196d8290ef45.png)

**Comment by yumiki** [comment]
I got the same issue. In my case I got multiple network manager running together. It was systemd-resolved and NetworkManager. 
And it seems that the only one that working pretty well is NetworkManager. 
Tell me if you need help to disable systemd-resolved

**Comment by jacknodles** [comment]
> I got the same issue. In my case I got multiple network manager running together. It was systemd-resolved and NetworkManager. And it seems that the only one that working pretty well is NetworkManager. Tell me if you need help to disable systemd-resolved
> 
> EDIT: I remember too that I got one missing driver for my network card, I will try to tell you as soon as possible what I installed.

how? please help

**Comment by pedrodesu** [comment]
Same problem here, it truly is a headache. I have but one network manager running, NetworkManager (I don't even run systemd on my computer), so it's not a matter of having multiple network managers running. As an ugly workaround, simply set xrandr with the layout you desire and save it to some place such as ~/.Xsession

Nonetheless, I hope this gets a fix, cutefish has tremendous potential.

**Comment by roman0671** [comment]
Same Issue here, on my Arch Linux PC as well is in my QEMU VMs. Will there be a fix released?

**Comment by pedrodesu** [comment]
> Same Issue here, on my Arch Linux PC as well is in my QEMU VMs. Will there be a fix released?

I'm afraid cutefish don't seem very enthusiastic about this issue. let's give it time and hope for the best. cutefish is probably the most beautiful DE for Linux, but is still in a very early release and has many bugs.

With that said, this one in particular and some other bugs made me switch DE some weeks ago, against my liking. Hope we get an update on this.

**Comment by roman0671** [comment]
Yeah, same situation here, its very sad

**Comment by HougeLangley** [comment]
This project has dead

**Comment by roman0671** [comment]
What do you mean?

**Comment by Ar7hurz1nh0** [comment]
the issue seems to be fixed on the git version, if you are still having any issues, even after updating, you should create a new issue

**Comment by pedrodesu** [comment]
When will this be uploaded to community repo? It's not even feasible to have Cutefish DE's git fully installed since one of the packages throws an error when attempting to install. (https://github.com/cutefishos/qt-plugins/issues/4)

**Comment by Ar7hurz1nh0** [comment]
it should be safe to only update the cutefish/settings to the git version, although I haven't tried anything

**Comment by pedrodesu** [comment]
It cannot be installed. At least when I replied, building the git version would throw a compilation error. I also mentioned that in my last reply.

**Comment by pedrodesu** [comment]
This is solved.
